<a href="https://colab.research.google.com/github/MRafaydev/Data_Cleaning/blob/main/Pre_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA PREPROCESSING**

**Upload Libaries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv("/content/drive/MyDrive/zameen-property-data.csv")
df.head()

property_id  ...                                         agent
0       237062  ...                                           NaN
1       346905  ...                                           NaN
2       386513  ...                                           NaN
3       656161  ...                                           NaN
4       841645  ...  Muhammad Junaid Ceo Muhammad Shahid Director

[5 rows x 17 columns]

In [3]:
df2=df.drop(['city', 'province_name',"location","page_url","property_type","area","purpose","agency","agent","date_added"], axis=1)
df2.head()

property_id  location_id     price   latitude  longitude  baths  bedrooms
0       237062         3325  10000000  33.679890  73.012640      2         2
1       346905         3236   6900000  33.700993  72.971492      3         3
2       386513          764  16500000  33.631486  72.926559      6         5
3       656161          340  43500000  33.707573  73.151199      4         4
4       841645         3226   7000000  33.492591  73.301339      3         3

In [13]:
X=df2.drop(["price"],axis=1)
y=df2["price"]
print("shape of X = ", X.shape)
print("shape of y = ", y.shape)

shape of X =  (168446, 6)
shape of y =  (168446,)


In [5]:
X.describe()

property_id    location_id  ...          baths       bedrooms
count  1.684460e+05  168446.000000  ...  168446.000000  168446.000000
mean   1.559626e+07    4375.936395  ...       2.874227       3.179422
std    2.251207e+06    3776.561581  ...       2.463400       1.971401
min    8.657500e+04       1.000000  ...       0.000000       0.000000
25%    1.488320e+07    1058.000000  ...       0.000000       2.000000
50%    1.665851e+07    3286.000000  ...       3.000000       3.000000
75%    1.708662e+07    7220.000000  ...       4.000000       4.000000
max    1.735772e+07   14220.000000  ...     403.000000      68.000000

[8 rows x 6 columns]

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   property_id  168446 non-null  int64  
 1   location_id  168446 non-null  int64  
 2   latitude     168446 non-null  float64
 3   longitude    168446 non-null  float64
 4   baths        168446 non-null  int64  
 5   bedrooms     168446 non-null  int64  
dtypes: float64(2), int64(4)
memory usage: 7.7 MB


In [7]:
X.isnull().sum()

property_id    0
location_id    0
latitude       0
longitude      0
baths          0
bedrooms       0
dtype: int64

In [8]:
y.isnull().sum()

0

For missing values using sciket learn and imputer
#from sklearn.preprocessing import imputer

#imputer = Imputer(missing_values="naN",strategy="mean",fill_values="None")

#imputer = imputer,fit(X)
#imputer.transfrom(X)

**Convert data from into numeric values**

from sklearn.preprocessing import labelEncoder,OneHotencoder

label_encoder_X=LableEncoder()

X[:values of block]=label_encoder_X.fit_transform([:values])

Onehotencoder = OneHotEncoder(categorical_Features =[0])

X=label_encoder_X.fit_transform(X).toarray()




In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
X_train.head()

property_id  location_id   latitude  longitude  baths  bedrooms
37158      14536079         1057  31.584531  74.372978      3         3
120355     17054399         6043  33.641205  73.065770      0         3
20181      12732008         1483  24.805045  67.064323      7         6
124507     17076701         8885  24.908308  67.072070      2         2
143502     17218860         3337  33.645957  72.962472      0         0

In [29]:
y_train.head()

37158       3900000
120355        48000
20181     190000000
124507      6500000
143502        38000
Name: price, dtype: int64

**Standard Scaling**

In [94]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_test=sc_X.fit_transform(X_test)
X_train=sc_X.fit_transform(X_train)


In [95]:
X_test

array([[ 0.512329  ,  2.28773788, -1.32421791, -1.32091397,  0.06445469,
         0.427795  ],
       [ 0.75363975,  1.56862878,  0.40891806,  0.59992228, -1.26177412,
        -1.61746182],
       [-1.61438836, -0.77212039, -1.32892009, -1.34229992, -0.37762158,
        -0.59483341],
       ...,
       [-2.95496984, -0.78113245,  0.42178992,  1.02527298,  1.3906835 ,
         0.9391092 ],
       [ 0.62674794, -1.12120505,  1.01523485,  0.58026164,  1.3906835 ,
         0.9391092 ],
       [ 0.15168308,  0.66000142, -1.2908899 , -1.31893416, -0.37762158,
        -0.59483341]])

In [96]:
X_test

array([[ 0.512329  ,  2.28773788, -1.32421791, -1.32091397,  0.06445469,
         0.427795  ],
       [ 0.75363975,  1.56862878,  0.40891806,  0.59992228, -1.26177412,
        -1.61746182],
       [-1.61438836, -0.77212039, -1.32892009, -1.34229992, -0.37762158,
        -0.59483341],
       ...,
       [-2.95496984, -0.78113245,  0.42178992,  1.02527298,  1.3906835 ,
         0.9391092 ],
       [ 0.62674794, -1.12120505,  1.01523485,  0.58026164,  1.3906835 ,
         0.9391092 ],
       [ 0.15168308,  0.66000142, -1.2908899 , -1.31893416, -0.37762158,
        -0.59483341]])

In [10]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
y_pred = reg.predict(X_test)
y_pred

array([19106964.75825788, -3909674.70478542, 18507376.67616081, ...,
       34221341.93070152, 24679412.59039617, 13492385.84679398])

In [19]:
reg.score(X_test,y_test)

0.1104058337609005

In [14]:
print('- y_pred : ')
print(y_pred)
print('- y_test : ')
print(y_test)

- y_pred : 
[19106964.75825788 -3909674.70478542 18507376.67616081 ...
 34221341.93070152 24679412.59039617 13492385.84679398]
- y_test : 
89777      3300000
158067    12900000
14802      8000000
167977       60000
92118      5000000
            ...   
92512     80000000
130728    55000000
3396      45000000
114133      350000
63022      5000000
Name: price, Length: 33690, dtype: int64


In [17]:
print(y_pred.sum().mean())
print(y_test.sum().mean())

print("So called Accuracy ", y_pred.sum().mean()/y_test.sum().mean())

595074190418.5546
594609258591.0
So called Accuracy  1.000781911517248


In [23]:
pd.DataFrame(np.c_[X_test, y_test, y_pred], columns = ["property_id","location_id","latitude","longitude","baths","bedrooms","real_price","Orignal_price"])

property_id  location_id   latitude  ...  bedrooms  real_price  Orignal_price
0       16761552.0      13026.0  24.828138  ...       4.0   3300000.0   1.910696e+07
1       17303496.0      10313.0  31.415799  ...       0.0  12900000.0  -3.909675e+06
2       11985297.0       1482.0  24.810265  ...       2.0   8000000.0   1.850738e+07
3       17351321.0       3444.0  33.662782  ...       0.0     60000.0  -4.813935e+06
4       16794070.0       8954.0  24.959785  ...       2.0   5000000.0   1.161540e+07
...            ...          ...        ...  ...       ...         ...            ...
33685   16800908.0       1556.0  31.481966  ...       6.0  80000000.0   3.548783e+07
33686   17108873.0       1611.0  31.471132  ...       5.0  55000000.0   3.311397e+07
33687    8974573.0       1448.0  31.464725  ...       5.0  45000000.0   3.422134e+07
33688   17018518.0        165.0  33.720413  ...       5.0    350000.0   2.467941e+07
33689   15951601.0       6885.0  24.954818  ...       2.0   5000000.0   1.349239e+07

[33690 rows x 8 columns]